### ISSUE TITLE
Include Defaults Forgery 

### ISSUE THREAD

**Issue by orta** [ashfurrow/Forgeries#1]
https://github.com/artsy/energy/blob/master/ArtsyFolio%20Tests/Stubs/FakeUserDefaults.m
https://github.com/artsy/energy/blob/master/ArtsyFolio%20Tests/Stubs/FakeUserDefaults.h

**Comment by ashfurrow** [comment]
:clap:

**Comment by ashfurrow** [comment]
Not a fan of adding a dependency on OCMock for [this one method](https://github.com/artsy/energy/blob/98ef4a76de88c219a14cc5a218ebde1cd9275bf8/ArtsyFolio%20Tests/Stubs/FakeUserDefaults.m#L12-L18). Would you be amenable to keeping that in energy? Though it _does_ seem like a common use case? Maybe include a subspec? Can't think of a way to do it conditionally if OCMock is available.

**Comment by orta** [comment]
Should be able to use something [like this](https://github.com/artsy/energy/blob/master/Classes/Artwork/Paging/ARArtworkSetViewController.m#L15)

```
#if __has_include(<SafariServices/SafariServices.h>)
#import <SafariServices/SafariServices.h>
#endif
```

but I'm alright with removing it, TBH though, I'd do this on every app I write tests for.

**Comment by ashfurrow** [comment]
Yeah, don't really feel like taking it out completely is a good solution. I think wrapping the API in these preprocessor conditionals would be a good compromise.
