### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Forgeries#10]
[Quality index](https://cocoapods.org/pods/NSObject+Rx/quality) is low :cry: 

<img width="781" alt="screen shot 2015-11-21 at 11 50 06 am" src="https://cloud.githubusercontent.com/assets/498212/11319480/159eaf7a-9046-11e5-81de-92ce8ea51cbb.png">

**Comment by orta** [comment]
this should kinda be fixed in #11

**Comment by orta** [comment]
Is fixed
