### ISSUE TITLE
Protocol Extension

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Forgeries#16]
Instead of using C macros, which are terrible, and adding a category for every class that conforms to `UITraitEnvironment`, we ought to just use a Swift protocol extension. A friend sent in an example that replicates our existing functionality: https://gist.github.com/asmallteapot/cf91cca4fe692932fac9

This would be _way_ better. The only reason I didn't use this approach is because I tried but Xcode fought back, so I went with C macros (sometimes easier than fighting with Xcode!). But this is better.

**Comment by orta** [comment]
Don't think it's worth rushing to add swift code unless it really does add something useful, we're limiting the consumers of the library to people using frameworks then.

**Comment by ashfurrow** [comment]
Makes sense.
