### ISSUE TITLE
Add Tests/CI

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Forgeries#3]
Testing the gesture recognizer subclasses is very difficult, but the Defaults replacement should be testable. 

Add tests and add Travis CI integration.

**Comment by seanoshea** [comment]
Took a bash at the travis ci integration, but I'm having some issues with selecting the correct simulator:

```
xcodebuild: error: Failed to build workspace Forgeries with scheme forgeries-Example.
Reason: The run destination iPad 2 is not valid for Running the scheme 'forgeries-Example'.
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/74178586/log.txt is the full link to the log if you're interested and https://github.com/seanoshea/Forgeries/tree/ci is the branch I created to try to tackle this work. I believe iPad 2 is probably the first simulator in the list, so Xcode tries to run with it. I tried altering the xcodebuild command to specify the simulator, but wasn't sure which simulators to target.

Dunno if you've any preference for using slather for this too. I've used it in the past with coveralls and found it useful.

**Comment by ashfurrow** [comment]
Ah, that's my fault – I originally called it "forgeries" (lowercase 'f'), and changed it after. It's probably using the old target name somewhere. I'll take a look.

**Comment by ashfurrow** [comment]
I've made a few updates, pushed to the `ci` branch.

**Comment by ashfurrow** [comment]
OK, cool! So the project is set up with Circle CI. Once you pull the latest, all you need to do (in theory) is get the Xcode "Tests" target to run the tests, then Circle infers the rest. Slather and Coveralls sounds really cool! I've never used them – let me know if I can help.

**Comment by seanoshea** [comment]
Cool. I've used slather and coveralls in a different project (https://github.com/seanoshea/BluePlaquesLondon). I'll take a crack at getting it set up with the CI flow.

**Comment by seanoshea** [comment]
It appears that enabling iOS builds for circle-ci requires beta access. Have emailed their team to see what the deal is with that. FWIW, https://circleci.com/gh/seanoshea/Forgeries/2 is where it stands now with the Gemfile and slather:

```
Gem::InstallError: xcodeproj requires Ruby version >= 2.0.0.
```

Perhaps I'll try to get the ci build working first before trying any slather/coverage work. If you've any pointers on how to get around that issue (can we request a 2.0.0 version of ruby to be pre-installed on a circle-ci box), I'm all ears.

**Comment by seanoshea** [comment]
OK - have the tests running in https://circleci.com/gh/seanoshea/Forgeries/3:

```
** BUILD-TESTS SUCCEEDED ** (17269 ms)

=== RUN-TESTS ===

[Info] Collecting info for testables... (2057 ms)
run-test Tests.xctest (latest, iPhone 6, logic-test)
~ -[Tests testExample] (5 ms)
    -[Tests testPerformanceExample]
```

Now, I think I just have to enable a few flags for debug versions of the build (generating gcda files and whatnot) and try to get slather up and running.

**Comment by ashfurrow** [comment]
This repo is included in their iOS beta program. Once you send a pull request back to this repo, it'll run the tests, too. Let me know if I can help.

**Comment by ashfurrow** [comment]
This has been done, the little badge thingy is on the readme.

**Comment by seanoshea** [comment]
Cool - great to see it @ashfurrow
